spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/issue_tracker?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password:
  sql:
    init:
#      data-locations: classpath:data.sql
#      mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
#      ddl-auto: update
      format_sql: true

oauth2:
  github:
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}

  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    admin-key: ${KAKAO_ADMIN_KEY}

  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}

jwt:
  issuer: ${JWT_ISSUER}
  secret: ${JWT_SECRET}

logging:
  level.com.pio.oauth: debug
